services:
  ntqq-docker:
    # image: yuukinya/chronocat-docker
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: ntqq-docker
    restart: always
    ports:
      # - "宿主:内部"
      - "5500:5500"       #satori默认端口
      - "5900:5900"       #vnc默认端口
      - "6081:6081"       #noVNC默认端口
      - "8080:8080"     #red默认端口
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWD=vncpasswd
    volumes:
      - ./data/QQ:/root/.config/QQ #QQ数据固化目录，请先阅读README再使用